name: Semgrep Scan

on:
  push:
    branches: [main]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"  # or your custom rules
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          
